#!/usr/bin/env python
# -*- coding: utf-8 -*-
# http://weather.nsu.ru/

import urllib.request
import time
from sleekxmpp import ClientXMPP

xmpp_id = 'sayfudinova@xabber.org'
xmpp_pwd = '123456789'
to = 'sayfudinova@jabber.uk'
xmpp = ClientXMPP(xmpp_id, xmpp_pwd)
xmpp.connect()
xmpp.process()

while True:
    response = urllib.request.urlopen(urllib.request.Request('http://weather.nsu.ru/weather.xml'))
    str_page = str(response.read())
    index1 = str_page.find('current')
    index2 = str_page.find('/current')
    data = str_page[index1 + 8:index2 - 1]
    print(data)
    xmpp.send_message(to, 'Current temperature: ' + data + '°C')
    time.sleep(1)

client.disconnect()
